// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package authorisation

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Signup() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"d-flex flex-column justify-content-center p-2\"><div class=\"container rounded d-flex justify-content-center\"><div class=\"card w-100 card-green\" style=\"max-width: 40rem\"><div class=\"card-header text-center\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Sign up`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1></div><div class=\"card-body\"><style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `
						.img-label {
							border: #204712 2px solid;
						}
						.img-label:has(input[type="radio"]:checked) {
							border: white 2px solid;
						}
					`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style><form id=\"signup\"><div class=\"d-grid gap-2 mb-2\" style=\"grid-template-columns: repeat(5, 1fr);\"><label class=\"img-label rounded overflow-hidden\" for=\"image1\"><input class=\"image d-none\" type=\"radio\" id=\"image1\" name=\"profile\" value=\"1\"> <img class=\"w-100\" src=\"/static/imgs/1profile.png\" alt=\"Image 1\"></label> <label class=\"img-label rounded overflow-hidden\" for=\"image2\"><input class=\"image d-none\" type=\"radio\" id=\"image2\" name=\"profile\" value=\"2\"> <img class=\"w-100\" src=\"/static/imgs/2profile.png\" alt=\"Image 2\"></label> <label class=\"img-label rounded overflow-hidden\" for=\"image3\"><input class=\"image d-none\" type=\"radio\" id=\"image3\" name=\"profile\" value=\"3\"> <img class=\"w-100\" src=\"/static/imgs/3profile.png\" alt=\"Image 3\"></label> <label class=\"img-label rounded overflow-hidden\" for=\"image4\"><input class=\"image d-none\" type=\"radio\" id=\"image4\" name=\"profile\" value=\"4\"> <img class=\"w-100\" src=\"/static/imgs/4profile.png\" alt=\"Image 4\"></label> <label class=\"img-label rounded overflow-hidden\" for=\"image5\"><input class=\"image d-none\" type=\"radio\" id=\"image5\" name=\"profile\" value=\"5\"> <img class=\"w-100\" src=\"/static/imgs/5profile.png\" alt=\"Image 5\"></label></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := ` 5 pictures to click on (select) `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><input class=\"form-control mb-2\" type=\"text\" id=\"name\" name=\"name\" placeholder=\"Username\" required> <input class=\"form-control mb-4\" type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\" required><div style=\"display: grid;\n						grid-template-columns: 1fr 1fr;\n						gap: 1rem;\"><a href=\"/login\" class=\"btn btn-secondary\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `Log in`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a> <button class=\"btn btn-primary\" type=\"submit\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `Sign up`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></form></div></div></div></main><script src=\"/static/js/signup/form.js?version=2\" defer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
