
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (8, NULL, NULL, NULL, 'UB', 2.5, '/static/imgs/stocks/ub.png', '/static/imgs/stocks/ub.png', 1);
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (10, NULL, NULL, NULL, 'Thames', 5.5, '/static/imgs/stocks/thames.png', '/static/imgs/stocks/thames.png', 2);
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (12, NULL, NULL, NULL, 'Natwest', 9.0, '/static/imgs/stocks/natwest.png', '/static/imgs/stocks/natwest.png', 6);
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (7, NULL, NULL, NULL, 'Trusthouse Forte', 2.0, '/static/imgs/stocks/thf.png', '/static/imgs/stocks/thf.png', 4);
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (11, NULL, NULL, NULL, 'Saatchi & Saatchi', 7.5, '/static/imgs/stocks/S_and_S.png', '/static/imgs/stocks/S_and_S_secondary.png', 5);
INSERT INTO public.stocks (id, created_at, updated_at, deleted_at, name, starting_value, image_path, secondary_image_path, variation) VALUES (9, NULL, NULL, NULL, 'Legal & General', 4.0, '/static/imgs/stocks/legal_and_general.svg', '/static/imgs/stocks/legal_and_general_secondary.svg', 3);

INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (59, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (60, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (62, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (63, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (64, NULL, NULL, NULL, 8, 'UB Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (65, NULL, NULL, NULL, 8, 'UB Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (66, NULL, NULL, NULL, 8, 'UB Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (68, NULL, NULL, NULL, 8, 'UB Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (69, NULL, NULL, NULL, 8, 'UB Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (70, NULL, NULL, NULL, 8, 'UB Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (71, NULL, NULL, NULL, 9, 'Legal & General Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (72, NULL, NULL, NULL, 9, 'Legal & General Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (73, NULL, NULL, NULL, 9, 'Legal & General Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (75, NULL, NULL, NULL, 9, 'Legal & General Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (76, NULL, NULL, NULL, 9, 'Legal & General Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (77, NULL, NULL, NULL, 9, 'Legal & General Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (78, NULL, NULL, NULL, 10, 'Thames Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (79, NULL, NULL, NULL, 10, 'Thames Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (80, NULL, NULL, NULL, 10, 'Thames Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (81, NULL, NULL, NULL, 10, 'Thames Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (83, NULL, NULL, NULL, 10, 'Thames Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (84, NULL, NULL, NULL, 10, 'Thames Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (85, NULL, NULL, NULL, 10, 'Thames Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (86, NULL, NULL, NULL, 10, 'Thames Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (87, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 2.5', 2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (88, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (89, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (90, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (91, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (93, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (94, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (95, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (96, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (97, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -2.5', -2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (98, NULL, NULL, NULL, 12, 'Natwest Insight 3.0', 3.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (99, NULL, NULL, NULL, 12, 'Natwest Insight 2.5', 2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (100, NULL, NULL, NULL, 12, 'Natwest Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (101, NULL, NULL, NULL, 12, 'Natwest Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (102, NULL, NULL, NULL, 12, 'Natwest Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (103, NULL, NULL, NULL, 12, 'Natwest Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (105, NULL, NULL, NULL, 12, 'Natwest Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (106, NULL, NULL, NULL, 12, 'Natwest Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (107, NULL, NULL, NULL, 12, 'Natwest Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (108, NULL, NULL, NULL, 12, 'Natwest Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (109, NULL, NULL, NULL, 12, 'Natwest Insight -2.5', -2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (110, NULL, NULL, NULL, 12, 'Natwest Insight -3.0', -3.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (157, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (158, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (159, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (160, NULL, NULL, NULL, 7, 'Trusthouse Forte Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (161, NULL, NULL, NULL, 8, 'UB Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (162, NULL, NULL, NULL, 8, 'UB Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (163, NULL, NULL, NULL, 8, 'UB Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (164, NULL, NULL, NULL, 8, 'UB Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (165, NULL, NULL, NULL, 8, 'UB Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (166, NULL, NULL, NULL, 8, 'UB Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (167, NULL, NULL, NULL, 9, 'Legal & General Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (168, NULL, NULL, NULL, 9, 'Legal & General Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (169, NULL, NULL, NULL, 9, 'Legal & General Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (170, NULL, NULL, NULL, 9, 'Legal & General Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (171, NULL, NULL, NULL, 9, 'Legal & General Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (172, NULL, NULL, NULL, 9, 'Legal & General Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (173, NULL, NULL, NULL, 10, 'Thames Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (174, NULL, NULL, NULL, 10, 'Thames Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (175, NULL, NULL, NULL, 10, 'Thames Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (176, NULL, NULL, NULL, 10, 'Thames Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (177, NULL, NULL, NULL, 10, 'Thames Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (178, NULL, NULL, NULL, 10, 'Thames Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (179, NULL, NULL, NULL, 10, 'Thames Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (180, NULL, NULL, NULL, 10, 'Thames Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (181, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 2.5', 2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (182, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (183, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (184, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (185, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (186, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (187, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (188, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (189, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (190, NULL, NULL, NULL, 11, 'Saatchi & Saatchi Insight -2.5', -2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (191, NULL, NULL, NULL, 12, 'Natwest Insight 3.0', 3.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (192, NULL, NULL, NULL, 12, 'Natwest Insight 2.5', 2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (193, NULL, NULL, NULL, 12, 'Natwest Insight 2.0', 2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (194, NULL, NULL, NULL, 12, 'Natwest Insight 1.5', 1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (195, NULL, NULL, NULL, 12, 'Natwest Insight 1.0', 1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (196, NULL, NULL, NULL, 12, 'Natwest Insight 0.5', 0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (197, NULL, NULL, NULL, 12, 'Natwest Insight -0.5', -0.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (198, NULL, NULL, NULL, 12, 'Natwest Insight -1.0', -1.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (199, NULL, NULL, NULL, 12, 'Natwest Insight -1.5', -1.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (200, NULL, NULL, NULL, 12, 'Natwest Insight -2.0', -2.0);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (201, NULL, NULL, NULL, 12, 'Natwest Insight -2.5', -2.5);
INSERT INTO public.insights (id, created_at, updated_at, deleted_at, stock_id, description, value) VALUES (202, NULL, NULL, NULL, 12, 'Natwest Insight -3.0', -3.0);
