// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "stockmarket/models"
import "fmt"

type contextKey string

var CurrentUser contextKey = "current_user"

func GetCurrentUser(ctx context.Context) models.User {
	user, ok := ctx.Value(CurrentUser).(models.User)
	if ok {
		return user
	}

	return models.User{}
}

func IsLoggedIn(ctx context.Context) bool {
	user, ok := ctx.Value(CurrentUser).(models.User)
	return ok && user != models.User{}
}

var CurrentGame contextKey = "current_game"

func GetGame(ctx context.Context) models.Game {
	// get current game from context
	game := ctx.Value(CurrentGame).(models.Game)
	return game
}

func GetGameCurrentUser(ctx context.Context) models.User {
	// get current game from context
	game := ctx.Value(CurrentGame).(models.Game)
	fmt.Println("game:", game.ID)
	cu := game.CurrentUser
	return cu
}

func IsCurrentUserTurn(ctx context.Context) bool {
	fmt.Println("**", IsLoggedIn(ctx), GetGameCurrentUser(ctx).ID, ":::", GetCurrentUser(ctx).ID)
	return IsLoggedIn(ctx) && GetGameCurrentUser(ctx).ID == GetCurrentUser(ctx).ID
}

func helper() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `this is a helper! it's only here to stop compiler errors. what a world.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
